package BankApp;


/**
* BankApp/ClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank/src/idl/BankApp.idl
* Sunday, November 1, 2015 9:45:01 AM EST
*/

public interface ClientOperations 
{
  String openAccount (String bank, String firstName, String lastName, String emailAddress, String phoneNumber, String password);
  String getLoan (String bank, String accountNumber, String password, int loanAmount);
  String transferLoan (String loanID, String currentBank, String otherBank);
  String delayPayment (String bank, String loanID, int currentDueDate, int newDueDate);
  String printCustomerInfo (String bank);
} // interface ClientOperations
