package BankApp;


/**
* BankApp/ClientPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BankApp.idl
* Wednesday, October 28, 2015 10:27:06 PM EDT
*/

public abstract class ClientPOA extends org.omg.PortableServer.Servant
 implements BankApp.ClientOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("openAccount", new java.lang.Integer (0));
    _methods.put ("getLoan", new java.lang.Integer (1));
    _methods.put ("transferLoan", new java.lang.Integer (2));
    _methods.put ("delayPayment", new java.lang.Integer (3));
    _methods.put ("printCustomerInfo", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BankApp/Client/openAccount
       {
         String bank = in.read_string ();
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String emailAddress = in.read_string ();
         String phoneNumber = in.read_string ();
         String password = in.read_string ();
         BankApp.Account $result = null;
         $result = this.openAccount (bank, firstName, lastName, emailAddress, phoneNumber, password);
         out = $rh.createReply();
         BankApp.AccountHelper.write (out, $result);
         break;
       }

       case 1:  // BankApp/Client/getLoan
       {
         String bank = in.read_string ();
         String accountNumber = in.read_string ();
         String password = in.read_string ();
         int loanAmount = in.read_long ();
         BankApp.Loan $result = null;
         $result = this.getLoan (bank, accountNumber, password, loanAmount);
         out = $rh.createReply();
         BankApp.LoanHelper.write (out, $result);
         break;
       }

       case 2:  // BankApp/Client/transferLoan
       {
         String loanID = in.read_string ();
         String currentBank = in.read_string ();
         String otherBank = in.read_string ();
         BankApp.Loan $result = null;
         $result = this.transferLoan (loanID, currentBank, otherBank);
         out = $rh.createReply();
         BankApp.LoanHelper.write (out, $result);
         break;
       }

       case 3:  // BankApp/Client/delayPayment
       {
         String bank = in.read_string ();
         String loanID = in.read_string ();
         int currentDueDate = in.read_long ();
         int newDueDate = in.read_long ();
         String $result = null;
         $result = this.delayPayment (bank, loanID, currentDueDate, newDueDate);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // BankApp/Client/printCustomerInfo
       {
         String bank = in.read_string ();
         String $result = null;
         $result = this.printCustomerInfo (bank);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BankApp/Client:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Client _this() 
  {
    return ClientHelper.narrow(
    super._this_object());
  }

  public Client _this(org.omg.CORBA.ORB orb) 
  {
    return ClientHelper.narrow(
    super._this_object(orb));
  }


} // class ClientPOA
