package BankApp;


/**
* BankApp/Client.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank/src/idl/BankApp.idl
* Sunday, November 1, 2015 9:45:01 AM EST
*/

public interface Client extends ClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Client
