package BankApp;

/**
* BankApp/ClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BankApp.idl
* Wednesday, October 28, 2015 10:27:06 PM EDT
*/

public final class ClientHolder implements org.omg.CORBA.portable.Streamable
{
  public BankApp.Client value = null;

  public ClientHolder ()
  {
  }

  public ClientHolder (BankApp.Client initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankApp.ClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankApp.ClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankApp.ClientHelper.type ();
  }

}
