package BankApp;


/**
* BankApp/Client.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BankApp.idl
* Wednesday, October 28, 2015 10:27:06 PM EDT
*/

public interface Client extends ClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Client
