package BankApp;


/**
* BankApp/Client.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/BankApp.idl
* Saturday, October 31, 2015 11:00:25 AM EDT
*/

public interface Client extends ClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Client
